### ISSUE TITLE
Code Realization Question about Offset Computation

### ISSUE THREAD

**Issue by lidongyv** [microsoft/RepPoints#21]
In the reppoints_head.py line 278.
dcn_offset = pts_out_init_grad_mul - dcn_base_offset
is there any reason that u use the prediction offset minus the base grid?
somehow, plus operation make sense, what is that mean if u use minus?

**Comment by xuyongzhi** [comment]
In the reppoints_head.py line 278. It seems the points offset is pts_out_init - dcn_base_offset. 
```
  dcn_offset = pts_out_init_grad_mul - dcn_base_offset
```
However, in the reppoints_head.py line 424, it seems the points offset is just pts_out_init.
```
pts_coordinate_preds_init = self.offset_to_pts(center_list,
                                                       pts_preds_init)
````
Sincerely thanks if anyone could answer this!
