### ISSUE TITLE
Why you assign the gt boxes to point sets by knn instead of by center?

### ISSUE THREAD

**Issue by MendelXu** [microsoft/RepPoints#4]
Nice job. I'm reading the code for more details and I find it is mentioned in the paper that" the projection of this ground-truth object’s center point locate within this feature map bin"  . However in this line, it said that a point set should be attached with a gt box which is its nearest gt box and the point set is in this gt box's k nearest neighbors. Doesn't this mean any prediction around the center point of a gt box and in its k nearest neighbors will be positive?
https://github.com/microsoft/RepPoints/blob/cac17da18b54c800db1565cf39a2723f6755b96c/src/reppoints_assigner/point_assigner.py#L32
Sincerely thanks if you cloud reply to me.

**Comment by yangze0930** [comment]
Thanks for your interests! In fact, the situation where k=1 in knn assignment is equivalent to using center point assignment.
